-- MySQL Script generated by MySQL Workbench
-- 09/01/15 23:09:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdAlpha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdAlpha` ;

-- -----------------------------------------------------
-- Schema bdAlpha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdAlpha` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `bdAlpha` ;

-- -----------------------------------------------------
-- Table `app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `app_user` (
  `id` BIGINT(20) NOT NULL COMMENT '',
  `account_expired` BIT(1) NULL COMMENT '',
  `account_locked` BIT(1) NULL COMMENT '',
  `address` VARCHAR(150) NULL COMMENT '',
  `city` VARCHAR(50) NULL COMMENT '',
  `country` VARCHAR(100) NULL COMMENT '',
  `postal_code` VARCHAR(15) NULL COMMENT '',
  `province` VARCHAR(100) NULL COMMENT '',
  `credentials_expired` BIT(1) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `account_enabled` BIT(1) NULL COMMENT '',
  `first_name` VARCHAR(50) NULL COMMENT '',
  `last_name` VARCHAR(50) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `password_hint` VARCHAR(255) NULL COMMENT '',
  `phone_number` VARCHAR(255) NULL COMMENT '',
  `username` VARCHAR(50) NULL COMMENT '',
  `version` INT(11) NULL COMMENT '',
  `website` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(64) NULL COMMENT '',
  `name` VARCHAR(25) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_role` (
  `user_id` BIGINT(20) NOT NULL COMMENT '',
  `role_id` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `role_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suggestion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `suggestion` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` BIGINT(20) NULL COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dish` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dish` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  `photo` VARCHAR(255) NULL COMMENT '',
  `category_id` BIGINT(20) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rate` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` BIGINT(20) NULL COMMENT '',
  `dish_id` BIGINT(20) NULL COMMENT '',
  `rate` INT(3) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `preference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `preference` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `preference` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` BIGINT(20) NULL COMMENT '',
  `dish_id` BIGINT(20) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `menu` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  `mondayDate` DATE NULL COMMENT '',
  `monday` BIGINT(20) NULL COMMENT '',
  `mondayState` BIT(1) NULL COMMENT '',
  `tuesdayDate` DATE NULL COMMENT '',
  `tuesday` BIGINT(20) NULL COMMENT '',
  `tuesdayState` BIT(1) NULL COMMENT '',
  `wednesdayDate` DATE NULL COMMENT '',
  `wednesday` BIGINT(20) NULL COMMENT '',
  `wednesdayState` BIT(1) NULL COMMENT '',
  `thursdayDate` DATE NULL COMMENT '',
  `thursday` BIGINT(20) NULL COMMENT '',
  `thursdayState` BIT(1) NULL COMMENT '',
  `fridayDate` DATE NULL COMMENT '',
  `friday` BIGINT(20) NULL COMMENT '',
  `fridayState` BIT(1) NULL COMMENT '',
  `saturdayDate` DATE NULL COMMENT '',
  `saturday` BIGINT(20) NULL COMMENT '',
  `saturdayState` BIT(1) NULL COMMENT '',
  `sundayDate` DATE NULL COMMENT '',
  `sunday` BIGINT(20) NULL COMMENT '',
  `sundayState` BIT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `weeklyplan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weeklyplan` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `weeklyplan` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` BIGINT(20) NULL COMMENT '',
  `mondayTemp` BIT(1) NULL COMMENT '',
  `monday` BIT(1) NULL COMMENT '',
  `tuesdayTemp` BIT(1) NULL COMMENT '',
  `tuesday` BIT(1) NULL COMMENT '',
  `wednesdayTemp` BIT(1) NULL COMMENT '',
  `wednesday` BIT(1) NULL COMMENT '',
  `thursdayTemp` BIT(1) NULL COMMENT '',
  `thursday` BIT(1) NULL COMMENT '',
  `fridayTemp` BIT(1) NULL COMMENT '',
  `friday` BIT(1) NULL COMMENT '',
  `saturdayTemp` BIT(1) NULL COMMENT '',
  `saturday` BIT(1) NULL COMMENT '',
  `sunday` BIT(1) NULL COMMENT '',
  `sundayTemp` BIT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
